BOARD_TAG    = atmega644
MONITOR_PORT = /dev/tty.usbserial*
ARDUINO_LIBS = Wire EEPROM DS1307RTC Time alphafive

ARDUINO_DIR   = /Applications/Arduino.app/Contents/Resources/Java
ARDMK_DIR     = /usr/local/CrossPack-AVR
AVR_TOOLS_DIR = /usr/local/CrossPack-AVR
USER_LIB_PATH = /Users/nic/Documents/Arduino/libraries
ALTERNATE_CORE_PATH = /Applications/Arduino.app/Contents/Resources/Java/hardware/sanguino
ARDUINO_LIB_PATH = /Applications/Arduino.app/Contents/Resources/Java/libraries
AVRDUDE_ARD_BAUDRATE = 38400

include Arduino.mk